(******************************************************************)
(* DO NOT EDIT THIS FILE                                          *)
(******************************************************************)

let check_interp_file : string -> unit = Main.interp_file
let check_interp_expr : Checker.Context.t -> Eval.env -> string -> 
                        (string,Main.error) result = Main.interp_expr

module type AuthorsSig = sig
  val hours_worked : int list
end

module AuthorsCheck : AuthorsSig = Authors
